### ISSUE TITLE
OCR (Image To Text Solver) 

### ISSUE THREAD

**Issue by ecriminals** [Dionis1902/AccountGeneratorHelper#7]
Just returns a blank response lol. Also idea add https://temp-mail.org/en/ to the list of supported temp-mail.

**Comment by Dionis1902** [comment]
Ok, thx, i will try add this in another update

**Comment by Dionis1902** [comment]
Sorry but this service have cloudflare protection

**Comment by Dionis1902** [comment]
yes, but in most cases then a captcha is given

**Comment by Dionis1902** [comment]
Ok i will try

**Comment by Dionis1902** [comment]
No thank you if i ask for help

**Comment by Dionis1902** [comment]
Added in version [1.0.13](https://github.com/Dionis1902/AccountGeneratorHelper/releases/tag/1.0.13)
