### ISSUE TITLE
Is there no way to generate a random gmail from gmailnator?

### ISSUE THREAD

**Issue by Wikileas** [Dionis1902/AccountGeneratorHelper#8]
I am writing to request a feature or documentation on how to generate random emails with Gmailnator. As a user of this package, I find it useful to generate random emails for various purposes, such as creating accounts on websites or testing email-related features in my code.

However, I noticed that Gmailnator currently does not provide a built-in method to generate random emails. The only way to set an email address is to use the gmailnator website, which has a certain pattern (e.g. be.at.r.ic.eallen03.3@gmail.com)

I would like to request a feature that allows users to generate random email addresses using Gmailnator. Ideally, this feature should make a valid Gmailnator gmail, since randomization does not seems to work.

Alternatively, if there is already a way to generate random emails with Gmailnator, I would appreciate if this feature could be documented in the package's documentation or README file, so that users can easily find and use it.

Thank you for your attention and for maintaining this useful package, really appreciate it, let me know if I was somehow rude by that.

**Comment by Dionis1902** [comment]
Unfortunately, it is not possible to create truly random gmail accounts for the reason that they have to be created, that's why gmailnator has a database of ready-made accounts. In the next update I plan to add the creation of random emails with your custom domain, then you will be able to generate an unlimited number of truly random emails

**Comment by Wikileas** [comment]
> Unfortunately, it is not possible to create truly random gmail accounts for the reason that they have to be created, that's why gmailnator has a database of ready-made accounts. In the next update I plan to add the creation of random emails with your custom domain, then you will be able to generate an unlimited number of truly random emails

There is a service called "tempmail.lol" most of their domains aren't banned yet, if you want to, I can make a PR to implement it later.

**Comment by Dionis1902** [comment]
Thx for info, i will add support this service in next update

**Comment by Dionis1902** [comment]
Added in verision 1.0.11
